/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.ScrollPaneLayout;

/**
 *
 * @author cbaidon45
 */
public class GUI extends javax.swing.JFrame {
int count=0;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jButton1)
                .addContainerGap(310, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
 if(count==0)
 {
  GridLayout Layout1 =new GridLayout(0,3,20,20);
     FlowLayout Layout2=new FlowLayout();
     
   
  //ScrollPaneLayout Scrollable= new ScrollPaneLayout();
  //jScrollPane1.setLayout(Scrollable);
  //jScrollPane1.setLayout(Layout1);
  
  jPanel1.setLayout(Layout2);
 }
    JComboBox[] combo1 = new JComboBox[100];
    JComboBox[] combo2 = new JComboBox[100];
    JTextField[] text1 = new JTextField[100];
    
    text1[0]=new JTextField();
    text1[1]=new JTextField();
    text1[2]=new JTextField();
    text1[3]=new JTextField();
    text1[4]=new JTextField();
    text1[5]=new JTextField();
    text1[6]=new JTextField();
    text1[7]=new JTextField();
    text1[8]=new JTextField();
    text1[9]=new JTextField();
    
    combo1[0]=new JComboBox();
    combo1[1]=new JComboBox();
    combo1[2]=new JComboBox();
    combo1[3]=new JComboBox();
    combo1[4]=new JComboBox();
    combo1[5]=new JComboBox();
    combo1[6]=new JComboBox();
    combo1[7]=new JComboBox();
    combo1[8]=new JComboBox();
    combo1[9]=new JComboBox();
    
    combo2[0]=new JComboBox();
    combo2[1]=new JComboBox();
    combo2[2]=new JComboBox();
    combo2[3]=new JComboBox();
    combo2[4]=new JComboBox();
    combo2[5]=new JComboBox();
    combo2[6]=new JComboBox();
    combo2[7]=new JComboBox();
    combo2[8]=new JComboBox();
    combo2[9]=new JComboBox();
    
    
    combo1[0].setSize(300, 300);
    combo1[1].setSize(50, 50);
    combo1[2].setSize(50, 50);
    combo1[3].setSize(50, 50);
    combo1[4].setSize(50, 50);
    combo1[5].setSize(50, 50);
    combo1[6].setSize(50, 50);
    combo1[7].setSize(50, 50);
    combo1[8].setSize(50, 50);
    combo1[9].setSize(50, 50);
    
    combo2[0].setSize(50, 50);
    combo2[1].setSize(50, 50);
    combo2[2].setSize(50, 50);
    combo2[3].setSize(50, 50);
    combo2[4].setSize(50, 50);
    combo2[5].setSize(50, 50);
    combo2[6].setSize(50, 50);
    combo2[7].setSize(50, 50);
    combo2[8].setSize(50, 50);
    combo2[9].setSize(50, 50);
    
    text1[0].setSize(50, 50);
    text1[1].setSize(50, 50);
    text1[2].setSize(50, 50);
    text1[3].setSize(50, 50);
    text1[4].setSize(50, 50);
    text1[5].setSize(50, 50);
    text1[6].setSize(50, 50);
    text1[7].setSize(50, 50);
    text1[8].setSize(50, 50);
    text1[9].setSize(50, 50);
    
    
    
    jPanel1.add(combo1[count]);
    jPanel1.add(combo2[count]);
    jPanel1.add(text1[count]);
    
    //jScrollPane1.add(combo1[count]);
    //jScrollPane1.add(combo2[count]);
    //jScrollPane1.add(text1[count]);
    //jScrollPane1.revalidate();
    //jScrollPane1.repaint();
    
     //jPanel1.setLayout(new GridLayout(0,3,20,20)); 
     
     
     jPanel1.revalidate();
     jPanel1.repaint();
     
 
 count=count+1;
 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
